/**
 * SAHP Companion - Official Data Store
 * Generated from Official EN3 Patrolman & Highway Patrol Guide
 */
window.SAHP_DATA = {
  "penalCodes": [
    {
      "code": "P.C. 2.1.1",
      "title": "Possession of Cocaine in Small Quantities",
      "category": "Crimes Against Society",
      "fine": "$10,000 + Confiscation",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "starCount": 0,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Possession of no more than four (4)  units of cocaine."
    },
    {
      "code": "P.C. 2.1.2",
      "title": "Possession of Cocaine in Moderate Quantities",
      "category": "Crimes Against Society",
      "fine": "$30,000 + Confiscation",
      "fineAmount": 30000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "starCount": 0,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Between 5 to 8 units of cocaine (5-8)"
    },
    {
      "code": "P.C. 2.1.3",
      "title": "Possession of Cocaine with Intent to Supply",
      "category": "Crimes Against Society",
      "fine": "$55,000 + Confiscation",
      "fineAmount": 55000,
      "sentence": "30 months",
      "sentenceMonths": 30,
      "class": "Felony  (Class D)",
      "stars": "\u2b50\u2b50",
      "starCount": 2,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Possession of more than eight (8)  units of cocaine."
    },
    {
      "code": "P.C. 2.2.1",
      "title": "Possession of Cannabis in Small Quantities",
      "category": "Crimes Against Society",
      "fine": "$8,000 + Confiscation",
      "fineAmount": 8000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "starCount": 0,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Possession of no more than ten (10)  units of cannabis."
    },
    {
      "code": "P.C. 2.2.2",
      "title": "Possession of Cannabis in Moderate Quantities",
      "category": "Crimes Against Society",
      "fine": "$30,000 + Confiscation",
      "fineAmount": 30000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "starCount": 0,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Possession of eleven (11) or more  units of cannabis."
    },
    {
      "code": "P.C. 2.2.3",
      "title": "Possession of Cannabis with Intent to Supply",
      "category": "Crimes Against Society",
      "fine": "$55,000 + Confiscation",
      "fineAmount": 55000,
      "sentence": "30 months",
      "sentenceMonths": 30,
      "class": "Felony  (Class D)",
      "stars": "\u2b50\u2b50",
      "starCount": 2,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Selling any quantity of cannabis"
    },
    {
      "code": "P.C. 2.2.4",
      "title": "Cultivation of Cannabis in Small Quantities",
      "category": "Crimes Against Society",
      "fine": "$20,000 + Confiscation",
      "fineAmount": 20000,
      "sentence": "15 months",
      "sentenceMonths": 15,
      "class": "Felony  (Class E)",
      "stars": "\u2b50",
      "starCount": 1,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Cultivating five (5) or fewer units of cannabis."
    },
    {
      "code": "P.C. 2.2.5",
      "title": "Cultivation of Cannabis in Large Quantities",
      "category": "Crimes Against Society",
      "fine": "$40,000 + Confiscation",
      "fineAmount": 40000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony  (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Cultivating six (6) or more units of cannabis."
    },
    {
      "code": "P.C. 2.3",
      "title": "Usage of Illicit Substances in Public",
      "category": "Crimes Against Society",
      "fine": "$15,000 + Confiscation",
      "fineAmount": 15000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "starCount": 0,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Consuming cocaine or cannabis in a public place."
    },
    {
      "code": "P.C. 2.4.1",
      "title": "Possession of Prohibited Items in Small Quantities",
      "category": "Prohibited Items",
      "fine": "$15,000 + Confiscation",
      "fineAmount": 15000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "Infraction (Class A)",
      "stars": "-",
      "starCount": 0,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Possessing no more than three (3) units of any prohibited item."
    },
    {
      "code": "P.C. 2.4.2",
      "title": "Possession of Prohibited Items in Large Quantities",
      "category": "Prohibited Items",
      "fine": "$20,000 + Confiscation",
      "fineAmount": 20000,
      "sentence": "30 months",
      "sentenceMonths": 30,
      "class": "Felony (Class D)",
      "stars": "\u2b50\u2b50",
      "starCount": 2,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Possessing more than three (3) units of any prohibited item."
    },
    {
      "code": "P.C. 2.4.3",
      "title": "Sale of Prohibited Items in Public Shops",
      "category": "Prohibited Items",
      "fine": "$30,000 + Confiscation",
      "fineAmount": 30000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Selling any prohibited item in a public shop."
    },
    {
      "code": "P.C. 2.5.1",
      "title": "Carrying Without a License",
      "category": "Prohibited Items",
      "fine": "$20,000 + Confiscation",
      "fineAmount": 20000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "Infraction (Class A)",
      "stars": "-",
      "starCount": 0,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Carrying weapons without the proper license."
    },
    {
      "code": "P.C. 2.5.2",
      "title": "Overcarrying",
      "category": "Prohibited Items",
      "fine": "$20,000 + Confiscation",
      "fineAmount": 20000,
      "sentence": "30 months",
      "sentenceMonths": 30,
      "class": "Felony (Class D)",
      "stars": "\u2b50\u2b50",
      "starCount": 2,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Exceeding the carrying limit as  defined in the Gun Law."
    },
    {
      "code": "P.C. 2.5.3",
      "title": "Open Carrying",
      "category": "Prohibited Items",
      "fine": "$15,000 + Confiscation + Revocation of gun license",
      "fineAmount": 15000,
      "sentence": "30 months",
      "sentenceMonths": 30,
      "class": "Felony (Class D)",
      "stars": "\u2b50\u2b50",
      "starCount": 2,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Publicly displaying any object typically  used to harm others."
    },
    {
      "code": "P.C. 2.5.4",
      "title": "Possession of a Prohibited Weapon",
      "category": "Prohibited Items",
      "fine": "$15,000 + Confiscation",
      "fineAmount": 15000,
      "sentence": "30 months",
      "sentenceMonths": 30,
      "class": "Felony (Class D)",
      "stars": "\u2b50\u2b50",
      "starCount": 2,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Possessing one (1) weapon of prohibited origin."
    },
    {
      "code": "P.C. 2.5.5",
      "title": "Possession of Multiple Prohibited Weapons",
      "category": "Prohibited Items",
      "fine": "$30,000 + Confiscation",
      "fineAmount": 30000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Possessing two (2) or more weapons of prohibited origin."
    },
    {
      "code": "P.C. 2.5.6",
      "title": "Brandishing of a Weapon",
      "category": "Prohibited Items",
      "fine": "$25,000 + Confiscation + Revocation of gun license",
      "fineAmount": 25000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Publicly displaying or using a weapon with the intent to scare (aiming at someone, shooting in the air etc.)"
    },
    {
      "code": "P.C. 2.5.7",
      "title": "Possession of State-Issued Articles",
      "category": "Prohibited Items",
      "fine": "$40,000 + Confiscation",
      "fineAmount": 40000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Possessing state-issued weaponry or unique equipment"
    },
    {
      "code": "P.C. 2.5.8",
      "title": "Discharging a Weapon in a Public Place",
      "category": "Prohibited Items",
      "fine": "$15,000 + Confiscation + Revocation of gun license",
      "fineAmount": 15000,
      "sentence": "15 months",
      "sentenceMonths": 15,
      "class": "Felony (Class E)",
      "stars": "\u2b50",
      "starCount": 1,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Firing any weapon in a public area."
    },
    {
      "code": "P.C. 2.6.1",
      "title": "Non-lethal Battery",
      "category": "Prohibited Items",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "15 months",
      "sentenceMonths": 15,
      "class": "Felony (Class E)",
      "stars": "\u2b50",
      "starCount": 1,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Intentional infliction of bodily harm without the use of firearms"
    },
    {
      "code": "P.C. 2.6.2",
      "title": "Manslaughter",
      "category": "Prohibited Items",
      "fine": "$20,000",
      "fineAmount": 20000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Unintentionally causing the death of another person."
    },
    {
      "code": "P.C. 2.6.3",
      "title": "Assault by Threat",
      "category": "Prohibited Items",
      "fine": "$20,000",
      "fineAmount": 20000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Verbal threats where there is a likelihood of the threat being carried out."
    },
    {
      "code": "P.C. 2.6.4",
      "title": "Attempted Murder",
      "category": "Prohibited Items",
      "fine": "$35,000",
      "fineAmount": 35000,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Attempting to murder another person either directly or indirectly."
    },
    {
      "code": "P.C. 2.6.5",
      "title": "Murder Through Hostile Action",
      "category": "Prohibited Items",
      "fine": "$35,000",
      "fineAmount": 35000,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Intentionally killing another person without prior planning."
    },
    {
      "code": "P.C. 2.6.6",
      "title": "Rape / Sexual Assault",
      "category": "Prohibited Items",
      "fine": "$55,000",
      "fineAmount": 55000,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Committing sexual acts through  intercourse or penetration against  the person\u2019s will."
    },
    {
      "code": "P.C. 2.7.1",
      "title": "Failure to Act",
      "category": "Prohibited Items",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "15 months",
      "sentenceMonths": 15,
      "class": "Felony (Class E)",
      "stars": "\u2b50",
      "starCount": 1,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Abandoning a person in life-threatening danger who cannot help themselves."
    },
    {
      "code": "P.C. 2.7.2",
      "title": "Refusal of Duty to Act",
      "category": "Prohibited Items",
      "fine": "Dismissal from the org",
      "fineAmount": 0,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "A civil servant refusing to act in the best interest of the public."
    },
    {
      "code": "P.C. 2.7.3",
      "title": "Failure to Act by a Civil Servant",
      "category": "Prohibited Items",
      "fine": "Dismissal from the org",
      "fineAmount": 0,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "A civil servant abandoning a person in life-threatening danger."
    },
    {
      "code": "P.C. 2.7.4",
      "title": "Negligence I",
      "category": "Prohibited Items",
      "fine": "$35,000",
      "fineAmount": 35000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "A public servant\u2019s dishonest or negligent  behavior leading to significant violations  of citizens\u2019 rights,  organizational interests,  or government interests."
    },
    {
      "code": "P.C. 2.7.4.1",
      "title": "Negligence II",
      "category": "Prohibited Items",
      "fine": "$40,000",
      "fineAmount": 40000,
      "sentence": "30 months",
      "sentenceMonths": 30,
      "class": "Felony (Class D)",
      "stars": "\u2b50\u2b50",
      "starCount": 2,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "A public servant\u2019s dishonest or negligent behavior leading to minor violations or no injury."
    },
    {
      "code": "P.C. 2.8.1",
      "title": "Kidnapping",
      "category": "Prohibited Items",
      "fine": "$35,000",
      "fineAmount": 35000,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Abduction and unlawful confinement of a person against their will."
    },
    {
      "code": "P.C. 2.8.2",
      "title": "Taking a Hostage",
      "category": "Prohibited Items",
      "fine": "$50,000",
      "fineAmount": 50000,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Holding a person as security for the fulfillment of a condition."
    },
    {
      "code": "P.C. 2.8.3",
      "title": "Unlawful Detention",
      "category": "Prohibited Items",
      "fine": "$20,000",
      "fineAmount": 20000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Depriving an individual of their freedom without legal justification or authority."
    },
    {
      "code": "P.C. 2.9.1",
      "title": "Disorderly Conduct",
      "category": "Prohibited Items",
      "fine": "$20,000",
      "fineAmount": 20000,
      "sentence": "15 months",
      "sentenceMonths": 15,
      "class": "Felony (Class E)",
      "stars": "\u2b50",
      "starCount": 1,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Engaging in conduct that disturbs the peace, morals, or safety of the public or a specific group."
    },
    {
      "code": "P.C. 2.9.2",
      "title": "Street Harassment",
      "category": "Prohibited Items",
      "fine": "$15,000",
      "fineAmount": 15000,
      "sentence": "30 months",
      "sentenceMonths": 30,
      "class": "Felony (Class D)",
      "stars": "\u2b50\u2b50",
      "starCount": 2,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Making rude, derogatory, or unwelcome verbal comments, whistles, or any form of verbal interaction."
    },
    {
      "code": "P.C. 2.9.3",
      "title": "Sexual Harassment",
      "category": "Prohibited Items",
      "fine": "$32,000",
      "fineAmount": 32000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Making unwelcome sexual advances, requests for sexual favors, or other verbal or physical harassment of a sexual nature."
    },
    {
      "code": "P.C. 2.9.4",
      "title": "Stalking",
      "category": "Prohibited Items",
      "fine": "$36,000",
      "fineAmount": 36000,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Repeatedly following or harassing another person, causing reasonable fear of injury or death."
    },
    {
      "code": "P.C. 2.9.5",
      "title": "Hooliganism",
      "category": "Prohibited Items",
      "fine": "$15,000",
      "fineAmount": 15000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Causing a tumultuous disturbance of the public peace."
    },
    {
      "code": "P.C. 2.9.6",
      "title": "Rioting",
      "category": "Prohibited Items",
      "fine": "$40,000",
      "fineAmount": 40000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Engaging in a tumultuous disturbance of the public peace by three or more persons acting with a common intent."
    },
    {
      "code": "P.C. 2.9.7",
      "title": "Violation of Regulations for a Meeting, Rally, Public Event, or Protest I",
      "category": "Prohibited Items",
      "fine": "$25,000",
      "fineAmount": 25000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Engaging in a public event or meeting that leads to law violations, disruption of peace, or property damage."
    },
    {
      "code": "P.C. 2.9.7.1",
      "title": "Violation of Regulations for a Meeting, Rally, Public Event, or Protest II",
      "category": "Prohibited Items",
      "fine": "$35,000",
      "fineAmount": 35000,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Engaging in the conduct described in \u00a72.9.7 involving the use of weapons."
    },
    {
      "code": "P.C. 2.9.7.2",
      "title": "Violation of Regulations for a Meeting, Rally, Public Event, or Protest III",
      "category": "Prohibited Items",
      "fine": "$45,000",
      "fineAmount": 45000,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Engaging in the conduct described in \u00a72.9.7 and \u00a72.9.7.1 that results in serious injury or death."
    },
    {
      "code": "P.C. 2.9.8",
      "title": "Spreading of Disease",
      "category": "Prohibited Items",
      "fine": "$15,000",
      "fineAmount": 15000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "",
      "stars": "-",
      "starCount": 0,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Intentionally transferring bacteria, viruses, or other germs to another person."
    },
    {
      "code": "P.C. 2.9.9",
      "title": "Indecent Exposure",
      "category": "Prohibited Items",
      "fine": "$20,000",
      "fineAmount": 20000,
      "sentence": "30 months",
      "sentenceMonths": 30,
      "class": "Felony (Class D)",
      "stars": "\u2b50\u2b50",
      "starCount": 2,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Intentionally exposing part of one\u2019s body in a place where such exposure is considered offensive to public decency."
    },
    {
      "code": "P.C. 2.9.10",
      "title": "Provoking",
      "category": "Prohibited Items",
      "fine": "$18,000",
      "fineAmount": 18000,
      "sentence": "30 months",
      "sentenceMonths": 30,
      "class": "Felony (Class D)",
      "stars": "\u2b50\u2b50",
      "starCount": 2,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Inducing someone to act or react by  deliberately annoying or harassing them."
    },
    {
      "code": "P.C. 2.9.11",
      "title": "Defamation of Character",
      "category": "Prohibited Items",
      "fine": "$50,000",
      "fineAmount": 50000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Damaging another person\u2019s reputation through slander or libel."
    },
    {
      "code": "P.C. 2.9.11.1",
      "title": "Assault of a Senior/Elderly Citizen",
      "category": "Prohibited Items",
      "fine": "$50,000",
      "fineAmount": 50000,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony      (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "The threat to cause bodily harm or the actual bodily harm to an elderly or senior citizen."
    },
    {
      "code": "P.C. 2.9.12",
      "title": "Complicity I",
      "category": "Prohibited Items",
      "fine": "$40,000",
      "fineAmount": 40000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Assisting another person in committing a crime, even if the actions differ from the crime itself."
    },
    {
      "code": "P.C. 2.9.13",
      "title": "Complicity II",
      "category": "Prohibited Items",
      "fine": "$25,000",
      "fineAmount": 25000,
      "sentence": "30 months",
      "sentenceMonths": 30,
      "class": "Felony (Class D)",
      "stars": "\u2b50\u2b50",
      "starCount": 2,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Failure to report or attempt to report a crime to the authorities, making one an accomplice."
    },
    {
      "code": "P.C. 2.10.1",
      "title": "Document Forgery",
      "category": "Prohibited Items",
      "fine": "$36,000",
      "fineAmount": 36000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Creating a false document to give the appearance of legal validity to an untrue fact."
    },
    {
      "code": "P.C. 2.10.2",
      "title": "Looting of an Automated Teller Machine (ATM)",
      "category": "Prohibited Items",
      "fine": "$15,000",
      "fineAmount": 15000,
      "sentence": "30 months",
      "sentenceMonths": 30,
      "class": "Felony (Class D)",
      "stars": "\u2b50\u2b50",
      "starCount": 2,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Unlawfully taking money from an ATM without significant bodily harm to any party involved."
    },
    {
      "code": "P.C. 2.10.3",
      "title": "Theft of Property",
      "category": "Prohibited Items",
      "fine": "$20,000",
      "fineAmount": 20000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Taking property from another without consent, through non-violent means."
    },
    {
      "code": "P.C. 2.10.4",
      "title": "Fraud",
      "category": "Prohibited Items",
      "fine": "$30,000",
      "fineAmount": 30000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Deliberate acts intended to obtain unauthorized benefits through deception or false representations."
    },
    {
      "code": "P.C. 2.10.5",
      "title": "Grand Theft Auto",
      "category": "Prohibited Items",
      "fine": "$32,000",
      "fineAmount": 32000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony      (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Unlawfully commandeering another person\u2019s vehicle with the intent to permanently or significantly deprive them of it."
    },
    {
      "code": "P.C. 2.10.6",
      "title": "Robbery",
      "category": "Prohibited Items",
      "fine": "$38,000",
      "fineAmount": 38000,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony      (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Taking property from a person or place by force or threat."
    },
    {
      "code": "P.C. 2.10.7",
      "title": "False Advertisement",
      "category": "Prohibited Items",
      "fine": "$15,000",
      "fineAmount": 15000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "Infraction (Class A)",
      "stars": "-",
      "starCount": 0,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Publicly distributing misleading or deceptive advertisements."
    },
    {
      "code": "P.C. 2.10.7.1",
      "title": "Illegal Advertisement",
      "category": "Prohibited Items",
      "fine": "$38,000",
      "fineAmount": 38000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "Infraction (Class C)",
      "stars": "-",
      "starCount": 0,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Advertising on platforms not designated for advertisements (e.g., Club radio)."
    },
    {
      "code": "P.C. 2.11.1",
      "title": "Attempted Suicide",
      "category": "Prohibited Items",
      "fine": "Mandatory mental health screening",
      "fineAmount": 0,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "Infraction (Class B)",
      "stars": "-",
      "starCount": 0,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Intentionally attempting to end  one\u2019s own life but failing to do so."
    },
    {
      "code": "P.C. 2.11.2",
      "title": "Conspiracy to Commit a Crime",
      "category": "Prohibited Items",
      "fine": "$20,000",
      "fineAmount": 20000,
      "sentence": "30 months",
      "sentenceMonths": 30,
      "class": "Felony      (Class D)",
      "stars": "\u2b50\u2b50",
      "starCount": 2,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Two or more individuals agreeing to engage in unlawful conduct with the intent to commit a crime."
    },
    {
      "code": "P.C. 2.11.3",
      "title": "Vandalism",
      "category": "Prohibited Items",
      "fine": "$23,000",
      "fineAmount": 23000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony      (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Deliberately damaging, destroying, defacing, or altering property without the owner\u2019s consent."
    },
    {
      "code": "P.C. 2.11.4",
      "title": "Illegal Fishing",
      "category": "Prohibited Items",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "Infraction (Class B)",
      "stars": "-",
      "starCount": 0,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Fishing in restricted or prohibited areas, such as the pond in Mirror Park."
    },
    {
      "code": "P.C. 2.11.5",
      "title": "Breach of Contract",
      "category": "Prohibited Items",
      "fine": "Agreed sum detailed in the contract",
      "fineAmount": 0,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony      (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Breaching the terms of a signed contractual agreement."
    },
    {
      "code": "P.C. 3.1.1",
      "title": "Participation in Terrorism",
      "category": "Crimes Against the State",
      "fine": "$50,000",
      "fineAmount": 50000,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony      (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Directly or indirectly participating in actions involving violence and intimidation for political aims."
    },
    {
      "code": "P.C. 3.1.2",
      "title": "Terroristic Acts",
      "category": "Crimes Against the State",
      "fine": "$50,000",
      "fineAmount": 50000,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony      (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "The unlawful use of violence and intimidation for political objectives."
    },
    {
      "code": "P.C. 3.1.3",
      "title": "Organization of Terrorism",
      "category": "Crimes Against the State",
      "fine": "$75,000",
      "fineAmount": 75000,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony      (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Recruiting individuals to join a political movement that uses terror to achieve its goals."
    },
    {
      "code": "P.C. 3.1.4",
      "title": "Leading a Terrorist Organization",
      "category": "Crimes Against the State",
      "fine": "$100,000",
      "fineAmount": 100000,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony      (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Providing guidance or leadership to a terrorist organization with political aims."
    },
    {
      "code": "P.C. 3.1.5",
      "title": "Formation of an Armed Group",
      "category": "Crimes Against the State",
      "fine": "$40,000",
      "fineAmount": 40000,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony      (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Creating or participating in the development of a group with the intent to commit criminal activities."
    },
    {
      "code": "P.C. 3.1.6",
      "title": "Banditry",
      "category": "Crimes Against the State",
      "fine": "$35,000",
      "fineAmount": 35000,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony      (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Engaging in organized crime involving threats of violence."
    },
    {
      "code": "P.C. 3.2",
      "title": "Obstruction of Justice",
      "category": "Crimes Against the State",
      "fine": "$35,000",
      "fineAmount": 35000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony      (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Wilfully interfering with the justice process."
    },
    {
      "code": "P.C. 3.3",
      "title": "Attempted Seizure of Power / Treason",
      "category": "Crimes Against the State",
      "fine": "$120,000",
      "fineAmount": 120000,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony      (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Attempting to unlawfully seize power or aiding state enemies."
    },
    {
      "code": "P.C. 3.4.1",
      "title": "Trespassing on Private Property",
      "category": "Crimes Against the State",
      "fine": "$15,000",
      "fineAmount": 15000,
      "sentence": "30 months",
      "sentenceMonths": 30,
      "class": "Felony      (Class D)",
      "stars": "\u2b50\u2b50",
      "starCount": 2,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Entering or loitering unlawfully on private land."
    },
    {
      "code": "P.C. 3.4.2",
      "title": "Trespassing on State Property",
      "category": "Crimes Against the State",
      "fine": "$25,000",
      "fineAmount": 25000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony      (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Entering or loitering unlawfully on state property."
    },
    {
      "code": "P.C. 3.4.3",
      "title": "Breaking and Entering",
      "category": "Crimes Against the State",
      "fine": "$25,000",
      "fineAmount": 25000,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony      (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Forcibly gaining unlawful access to  another's building."
    },
    {
      "code": "P.C. 3.5",
      "title": "Failure to Comply",
      "category": "Crimes Against the State",
      "fine": "$35,000",
      "fineAmount": 35000,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony      (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Intentionally refusing to cooperate with lawful requests from state employees."
    },
    {
      "code": "P.C. 3.6",
      "title": "Failure to Identify",
      "category": "Crimes Against the State",
      "fine": "$20,000",
      "fineAmount": 20000,
      "sentence": "30 months",
      "sentenceMonths": 30,
      "class": "Felony      (Class D)",
      "stars": "\u2b50\u2b50",
      "starCount": 2,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Intentionally refusing to provide state-issued identification upon lawful request."
    },
    {
      "code": "P.C. 3.7",
      "title": "Illegal Gambling",
      "category": "Crimes Against the State",
      "fine": "$25,000",
      "fineAmount": 25000,
      "sentence": "30 months",
      "sentenceMonths": 30,
      "class": "Felony      (Class D)",
      "stars": "\u2b50\u2b50",
      "starCount": 2,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Participating in or organizing unauthorized gambling activities."
    },
    {
      "code": "P.C. 3.8.1",
      "title": "Impersonation of a Civil Servant",
      "category": "Crimes Against the State",
      "fine": "$45,000",
      "fineAmount": 45000,
      "sentence": "30 months",
      "sentenceMonths": 30,
      "class": "Felony      (Class D)",
      "stars": "\u2b50\u2b50",
      "starCount": 2,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Unauthorized appropriation of powers  granted to a civil servant."
    },
    {
      "code": "P.C. 3.8.2",
      "title": "Impersonation of a Law Enforcement Officer",
      "category": "Crimes Against the State",
      "fine": "$35,000",
      "fineAmount": 35000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony      (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Unauthorized appropriation of powers  granted to a law enforcement officer."
    },
    {
      "code": "P.C. 3.9",
      "title": "Battery of a Public Servant",
      "category": "Crimes Against the State",
      "fine": "$15,000",
      "fineAmount": 15000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony      (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Intentional infliction of non-lethal bodily injury to a state employee."
    },
    {
      "code": "P.C. 3.10",
      "title": "Attempted Murder of a Public Servant",
      "category": "Crimes Against the State",
      "fine": "$50,000",
      "fineAmount": 50000,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony      (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Attempting to murder state or federal personnel."
    },
    {
      "code": "P.C. 3.11",
      "title": "False Reporting",
      "category": "Crimes Against the State",
      "fine": "$20,000",
      "fineAmount": 20000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony      (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Knowingly alerting authorities with incorrect details or reporting non-existent incidents."
    },
    {
      "code": "P.C. 3.12",
      "title": "Illegal Acquisition of State Secrets",
      "category": "Crimes Against the State",
      "fine": "$35,000",
      "fineAmount": 35000,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony      (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Acquiring state secrets through theft, deception, blackmail, or other illegal means."
    },
    {
      "code": "P.C. 3.13",
      "title": "Hiding or Destroying Evidence",
      "category": "Crimes Against the State",
      "fine": "$40,000",
      "fineAmount": 40000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony      (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Attempting to hide or destroy  evidence of a crime."
    },
    {
      "code": "P.C. 3.14",
      "title": "Negligence in Communication",
      "category": "Crimes Against the State",
      "fine": "$30,000",
      "fineAmount": 30000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony      (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "A public servant\u2019s serious ethical or moral violation through destructive communication."
    },
    {
      "code": "P.C. 3.15.1",
      "title": "Breach of Electoral Silence",
      "category": "Crimes Against the State",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "30 months",
      "sentenceMonths": 30,
      "class": "Felony      (Class D)",
      "stars": "\u2b50\u2b50",
      "starCount": 2,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Campaigning within five hundred (500) meters of a voting booth during active voting."
    },
    {
      "code": "P.C. 3.15.2",
      "title": "Blocking a Voting Site",
      "category": "Crimes Against the State",
      "fine": "$38,000",
      "fineAmount": 38000,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony      (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Intentionally blocking or limiting citizens\u2019 right to vote through threats or physical restraint."
    },
    {
      "code": "P.C. 3.15.3",
      "title": "Illegal Persuasion of Votes",
      "category": "Crimes Against the State",
      "fine": "$40,000",
      "fineAmount": 40000,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony      (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Persuading citizens to vote a certain way through material benefits or favors."
    },
    {
      "code": "P.C. 3.16.1",
      "title": "Active Bribery",
      "category": "Crimes Against the State",
      "fine": "$25,000",
      "fineAmount": 25000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony      (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Offering money or favors to influence a person in a position of trust."
    },
    {
      "code": "P.C. 3.16.2",
      "title": "Passive Bribery",
      "category": "Crimes Against the State",
      "fine": "$50,000",
      "fineAmount": 50000,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony      (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Accepting money or favors to influence the judgment or conduct of a person in a position of trust."
    },
    {
      "code": "P.C. 3.16.3",
      "title": "Quid Pro Quo",
      "category": "Crimes Against the State",
      "fine": "$50,000 + dismissal",
      "fineAmount": 50000,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony      (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Exchanging goods or services where one transfer is contingent upon the other."
    },
    {
      "code": "P.C. 3.17",
      "title": "Failure to Pay Fines",
      "category": "Crimes Against the State",
      "fine": "$25,000",
      "fineAmount": 25000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony      (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": true,
      "bailText": "No Bail Untill Fines Are Paid",
      "remarks": "Failure to pay fines imposed by law after committing an offense."
    },
    {
      "code": "P.C. 3.18.1",
      "title": "Evading Arrest",
      "category": "Crimes Against the State",
      "fine": "$25,000",
      "fineAmount": 25000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony      (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Fleeing from a police officer attempting to arrest, detain, or investigate."
    },
    {
      "code": "P.C. 3.18.2",
      "title": "Assisting Evasion of Arrest",
      "category": "Crimes Against the State",
      "fine": "$30,000",
      "fineAmount": 30000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony      (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Helping someone evade arrest."
    },
    {
      "code": "P.C. 3.19.1",
      "title": "Street Harassment Towards a Colleague",
      "category": "Crimes Against the State",
      "fine": "$25,000 + dismissal",
      "fineAmount": 25000,
      "sentence": "30 months",
      "sentenceMonths": 30,
      "class": "Felony      (Class D)",
      "stars": "\u2b50\u2b50",
      "starCount": 2,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Rude or unwelcome comments,  whistles, or other sexual verbal  interactions towards a colleague."
    },
    {
      "code": "P.C. 3.19.2",
      "title": "Hostile Work Environment",
      "category": "Crimes Against the State",
      "fine": "$50,000 + dmismissal",
      "fineAmount": 50000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony      (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Creating or supporting a work environment that is difficult or uncomfortable for others."
    },
    {
      "code": "P.C. 3.19.3",
      "title": "Sexual Harassment Towards a Colleague",
      "category": "Crimes Against the State",
      "fine": "$50,000 + dismissal",
      "fineAmount": 50000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony      (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Unwelcome sexual advances or  harassment towards a colleague."
    },
    {
      "code": "P.C. 3.19.4",
      "title": "Absence Without Leave",
      "category": "Crimes Against the State",
      "fine": "$50,000 + dismissal",
      "fineAmount": 50000,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony      (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Being absent without authority from a place of duty in the armed forces."
    },
    {
      "code": "P.C. 3.19.5",
      "title": "Provoking a Public Servant",
      "category": "Crimes Against the State",
      "fine": "$36,000",
      "fineAmount": 36000,
      "sentence": "30 months",
      "sentenceMonths": 30,
      "class": "Felony      (Class D)",
      "stars": "\u2b50\u2b50",
      "starCount": 2,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Inducing a state employee to act or react  as a result of deliberate harassment."
    },
    {
      "code": "P.C. 3.19.6",
      "title": "Tax Evasion",
      "category": "Crimes Against the State",
      "fine": "Unpaid taxes but no more than 100k",
      "fineAmount": 100,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony      (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Intentionally avoiding payment of  taxes owed to the government."
    },
    {
      "code": "P.C. 4.1",
      "title": "Exceeding Granted Powers I",
      "category": "Malfeasance",
      "fine": "$45,000",
      "fineAmount": 45000,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony      (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Public servant conduct that goes beyond their powers and violates the rights and legitimate interests of citizens, organizations, or legally protected public or government interests."
    },
    {
      "code": "P.C. 4.1.2",
      "title": "Exceeding Granted Powers II",
      "category": "Malfeasance",
      "fine": "$55,000",
      "fineAmount": 55000,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony      (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "The conduct described in \u00a74.1 if committed with: (a) The use of violence or a threat of its use; (b) The use of weaponry or special equipment; (c) Causing injury."
    },
    {
      "code": "P.C. 4.2",
      "title": "Ill-use of Granted Powers I",
      "category": "Malfeasance",
      "fine": "$40,000",
      "fineAmount": 40000,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony      (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "The misuse of public servant powers that contradict the organization's interests, leading to the violation of the rights and legitimate interests of citizens or organizations."
    },
    {
      "code": "P.C. 4.2.1",
      "title": "Ill-use of Granted Powers II",
      "category": "Malfeasance",
      "fine": "$60,000",
      "fineAmount": 60000,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony      (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Use of the powers granted to a public servant aiming to intervene or obstruct the process of detention or arrest, or an investigation."
    },
    {
      "code": "P.C. 4.2.2",
      "title": "Ill-use of Granted Powers III",
      "category": "Malfeasance",
      "fine": "$75,000",
      "fineAmount": 75000,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony      (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "The conduct described in \u00a74.2.1 if committed by an employee of an organization or a division authorized to conduct investigations of malfeasance."
    },
    {
      "code": "P.C. 4.3",
      "title": "Disobeying an Order",
      "category": "Malfeasance",
      "fine": "$25,000",
      "fineAmount": 25000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony      (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "To refuse and/or fail to follow a lawful order given by their superior officer."
    },
    {
      "code": "P.C. 4.3.1",
      "title": "Failure to Comply with an Executive Order, Court Decision, or Legitimate Order I",
      "category": "Malfeasance",
      "fine": "$35,000",
      "fineAmount": 35000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony      (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Non-compliance with a senior order  by a public servant, causing  significant violations of citizens'  rights, organizations' legitimate  interests, or government's legally  protected interests."
    },
    {
      "code": "P.C. 4.3.2",
      "title": "Failure to Comply with an Executive Order, Court Decision, or Legitimate Order II",
      "category": "Malfeasance",
      "fine": "$45,000",
      "fineAmount": 45000,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony      (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Deliberate non-compliance by a  public servant with an order  from a leader or a deputy of  that organization, carried out in  compliance with the current  order and not contradicting the law."
    },
    {
      "code": "P.C. 4.3.3",
      "title": "Failure to Comply with an Executive Order, Court Decision, or Legitimate Order III",
      "category": "Malfeasance",
      "fine": "$55,000",
      "fineAmount": 55000,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony      (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Non-compliance by a public servant  with an executive order, a court order,  or any other legitimate order carried  out on behalf of the Department of  Justice of San-Andreas or the  Government."
    },
    {
      "code": "P.C. 4.4",
      "title": "Professional Misconduct",
      "category": "Malfeasance",
      "fine": "$75,000",
      "fineAmount": 75000,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony      (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Conducting oneself in a manner that is professionally unsuitable, potentially dangerous to patients, incompetent, disruptive, abusive, or illegal."
    },
    {
      "code": "P.C. 4.5",
      "title": "Sabotage",
      "category": "Malfeasance",
      "fine": "$75,000",
      "fineAmount": 75000,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony      (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Deliberately destroying and/or damaging weaponry, ammunition, goods, or items of state property, to hinder or halt any operation initiated by the state."
    },
    {
      "code": "P.C. 4.6",
      "title": "Espionage",
      "category": "Malfeasance",
      "fine": "$75,000",
      "fineAmount": 75000,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony      (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "The crime of spying or secretly watching a person, company, government, etc., for the purpose of gathering secret information or detecting wrongdoing, and transferring such information to another organization or state."
    },
    {
      "code": "P.C. 4.7",
      "title": "Conduct Unbecoming",
      "category": "Malfeasance",
      "fine": "$75,000",
      "fineAmount": 75000,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony      (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Conduct on the part of a state employee that is contrary to the public interests and/or harms their standing in the profession in the eyes of the public."
    },
    {
      "code": "P.C. 4.8",
      "title": "Corruption",
      "category": "Malfeasance",
      "fine": "$75,000",
      "fineAmount": 75000,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony      (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Conducting oneself in a dishonest and/or  fraudulent manner by those residing in  power given by the state."
    },
    {
      "code": "P.C. 4.9",
      "title": "Disclosure of a State Secret",
      "category": "Malfeasance",
      "fine": "$75,000",
      "fineAmount": 75000,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony      (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Revealing state secrets through dishonest or  fraudulent behavior by those in positions of  power given by the state."
    },
    {
      "code": "P.C. 4.10",
      "title": "Violation of Radio Calls and Department Ethics Code",
      "category": "Malfeasance",
      "fine": "$10,000 + potential suspension/bl",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "",
      "stars": "-",
      "starCount": 0,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Inducing a state employee to charges for improper radio use and ethics breaches."
    },
    {
      "code": "P.C. 4.11",
      "title": "State Employee Promoting or Assisting in Illegal Activities",
      "category": "Malfeasance",
      "fine": "Falls under \u00a74.8 with judge approval",
      "fineAmount": 48,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony      (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "State employees involved in promoting or assisting illegal activities, such as using club radio for unlawful purposes (i.e., Club radio)."
    },
    {
      "code": "P.C. 4.12",
      "title": "Insulting a First Person",
      "category": "Malfeasance",
      "fine": "-",
      "fineAmount": 0,
      "sentence": "75 months",
      "sentenceMonths": 75,
      "class": "Felony      (Class A)",
      "stars": "\u2b50\u2b50\u2b50\u2b50\u2b50",
      "starCount": 5,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Anything that resembles or implies an allegation against a First person without compliance to immunity laws, shall be considered an attack against the most highest officials of the state."
    },
    {
      "code": "P.C. 5.1",
      "title": "Disobeying a Judicial Order",
      "category": "Judicial & Statute Crimes",
      "fine": "$40,000",
      "fineAmount": 40000,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony      (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Refusing or failing to comply with a lawful order issued by the Governor, Attorney General, or members of the judiciary chambers."
    },
    {
      "code": "P.C. 5.2",
      "title": "Disruption of a Trial",
      "category": "Judicial & Statute Crimes",
      "fine": "$25,000",
      "fineAmount": 25000,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony      (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Interfering with the orderly administration of justice, impairing the authority or dignity of the court, and/or disrupting the legal process within the courtroom."
    },
    {
      "code": "P.C. 5.3",
      "title": "Dishonoring a Judiciary Member",
      "category": "Judicial & Statute Crimes",
      "fine": "$35,000",
      "fineAmount": 35000,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony      (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Dishonoring the position of a judicial officer during the performance or in relation to the previous performance of their official duties."
    },
    {
      "code": "P.C. 5.4",
      "title": "Contempt of Court",
      "category": "Judicial & Statute Crimes",
      "fine": "$28,000",
      "fineAmount": 28000,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony      (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Disobeying a member of the judiciary chambers or otherwise failing to comply with an order of the court."
    },
    {
      "code": "P.C. 5.5",
      "title": "Ill-use of a Judicial Permit",
      "category": "Judicial & Statute Crimes",
      "fine": "$25,000 + revocation",
      "fineAmount": 25000,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony      (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Misconduct through the improper use of a judicial permit issued by the Department of Justice, contrary to the legislative guidelines established by law."
    },
    {
      "code": "P.C. 5.6",
      "title": "Forged Evidence",
      "category": "Judicial & Statute Crimes",
      "fine": "$20,000",
      "fineAmount": 20000,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony      (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Tampering with or forging evidence to  influence the outcome of a court case."
    },
    {
      "code": "P.C. 5.7",
      "title": "Perjury",
      "category": "Judicial & Statute Crimes",
      "fine": "$23,000",
      "fineAmount": 23000,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony      (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Swearing a false oath or making a false affirmation to tell the truth, whether spoken or written, concerning matters material to an official proceeding."
    },
    {
      "code": "P.C. 6.1.1",
      "title": "Minor Speed Violation",
      "category": "Traffic Regulations (Penal)",
      "fine": "$13,000",
      "fineAmount": 13000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "Infraction (Class C)",
      "stars": "-",
      "starCount": 0,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Speeding five (5) to thirty (30) kilometers per hour over the speed limit."
    },
    {
      "code": "P.C. 6.1.2",
      "title": "Mediocre Speed Violation",
      "category": "Traffic Regulations (Penal)",
      "fine": "$20,000",
      "fineAmount": 20000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "Infraction (Class B)",
      "stars": "-",
      "starCount": 0,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Speeding thirty-one (31) to sixty (60) kilometers per hour over the speed limit."
    },
    {
      "code": "P.C. 6.1.3",
      "title": "Major Speed Violation",
      "category": "Traffic Regulations (Penal)",
      "fine": "$25,000 + revocation of license",
      "fineAmount": 25000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "Infraction (Class A)",
      "stars": "-",
      "starCount": 0,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Speeding sixty-one (61) to ninety (90) kilometers per hour over the speed limit."
    },
    {
      "code": "P.C. 6.2",
      "title": "Jaywalking",
      "category": "Traffic Regulations (Penal)",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "Infraction (Class C)",
      "stars": "-",
      "starCount": 0,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Crossing a street carelessly or illegally, endangering oneself with traffic."
    },
    {
      "code": "P.C. 6.3",
      "title": "Abandonment of a Vehicle",
      "category": "Traffic Regulations (Penal)",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "Infraction (Class C)",
      "stars": "-",
      "starCount": 0,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Deliberately abandoning a vehicle in any public area or place where vehicles are not permitted."
    },
    {
      "code": "P.C. 6.4",
      "title": "Dangerous Transportation of People",
      "category": "Traffic Regulations (Penal)",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "Infraction (Class C)",
      "stars": "-",
      "starCount": 0,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Transporting a person in an unsafe manner, where seatbelts and/or proper posture for crash safety regulations are not adhered to."
    },
    {
      "code": "P.C. 6.5",
      "title": "Reckless Driving",
      "category": "Traffic Regulations (Penal)",
      "fine": "$35,000",
      "fineAmount": 35000,
      "sentence": "30 months",
      "sentenceMonths": 30,
      "class": "Felony      (Class D)",
      "stars": "\u2b50\u2b50",
      "starCount": 2,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Operating a vehicle in willful or wanton disregard for the traffic code."
    },
    {
      "code": "P.C. 6.5.1",
      "title": "Injury by Dangerous Driving",
      "category": "Traffic Regulations (Penal)",
      "fine": "$25,000",
      "fineAmount": 25000,
      "sentence": "45 months",
      "sentenceMonths": 45,
      "class": "Felony      (Class C)",
      "stars": "\u2b50\u2b50\u2b50",
      "starCount": 3,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Driving a motor vehicle in a manner that is significantly below the standard expected of a competent and careful driver, causing injury to any person involved."
    },
    {
      "code": "P.C. 6.5.2",
      "title": "Death by Dangerous Driving",
      "category": "Traffic Regulations (Penal)",
      "fine": "$55,000",
      "fineAmount": 55000,
      "sentence": "60 months",
      "sentenceMonths": 60,
      "class": "Felony      (Class B)",
      "stars": "\u2b50\u2b50\u2b50\u2b50",
      "starCount": 4,
      "noBail": false,
      "bailText": "FALSE",
      "remarks": "Driving a motor vehicle in a  manner that is significantly  below the standard expected of a  competent and careful driver,  resulting in the death of any  person involved."
    },
    {
      "code": "P.C. 6.6",
      "title": "Failure to Yield to an Emergency Service Vehicle",
      "category": "Traffic Regulations (Penal)",
      "fine": "$18,000",
      "fineAmount": 18000,
      "sentence": "15 months",
      "sentenceMonths": 15,
      "class": "Felony      (Class E)",
      "stars": "\u2b50",
      "starCount": 1,
      "noBail": true,
      "bailText": "TRUE",
      "remarks": "Failing to grant the right of way or refusing to give priority to an approaching emergency vehicle displaying lights and/or sounding sirens."
    }
  ],
  "prohibitedItems": [
    "All firearm without a serial number (XXX)",
    "State issued weapons or melees (FIB/SAHP/CP/GOV/NG)",
    "Ballistic vest with state markings (FIB/SAHP/CP/GOV/NG)",
    "Ballistic vest of any color except gray (Gang vests, Lui Vi etc.)",
    "Spare weapons parts",
    "State issued facial covering (Balaclava)",
    "Vehicle scanners",
    "USB drives containing malicious software",
    "Engine blockers",
    "Search Base Hack",
    "Lockpick or key sets",
    "Fake documentation (fake police ID)",
    "Anti-radar equipment",
    "Counterfeit money",
    "People scanner",
    "Alcohol (only in accordance with 2.4.3)",
    "State issued articles and licenses (only in accordance with 2.4.3)",
    "Medical supplies (only in accordance with 2.4.3)",
    "Stolen goods (TVs, Furniture, Box of things, etc.)"
  ],
  "trafficCodes": [
    {
      "code": "T.C. 2.1",
      "title": "Absence of a valid license plate",
      "category": "Moving & Driving Violations",
      "fine": "$5,000",
      "fineAmount": 5000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": ""
    },
    {
      "code": "T.C. 3.2.1(1)",
      "title": "Driving in the opposite lane of the road",
      "category": "Moving & Driving Violations",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": ""
    },
    {
      "code": "T.C. 3.2.1(2)",
      "title": "Driving the opposite lane of the highway",
      "category": "Moving & Driving Violations",
      "fine": "$15,000 + revocation of license",
      "fineAmount": 15000,
      "sentence": "30 months",
      "sentenceMonths": 30,
      "class": "Felony (Class D)",
      "stars": "\u2b50\u2b50",
      "noBail": false,
      "remarks": ""
    },
    {
      "code": "T.C. 3.2.2(1)",
      "title": "Stopping on the road for no reason",
      "category": "Moving & Driving Violations",
      "fine": "$15,000",
      "fineAmount": 15000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Stoping on the road for no reason and ignoring demands to continue moving"
    },
    {
      "code": "T.C. 3.2.2(2)",
      "title": "Stopping on the highway for no reason",
      "category": "Moving & Driving Violations",
      "fine": "$25,000 + revocation of ALL transport licenses",
      "fineAmount": 25000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "Infraction (Class A)",
      "stars": "-",
      "noBail": false,
      "remarks": "Stoping on the highway for no reason and ignoring demands to continue moving"
    },
    {
      "code": "T.C. 3.4.1",
      "title": "Driving on deserted sidewalks/bike paths",
      "category": "Moving & Driving Violations",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Driving on a sidewalk or bike path even if there are no people there"
    },
    {
      "code": "T.C. 3.4.2",
      "title": "Chaotic movement between lanes",
      "category": "Moving & Driving Violations",
      "fine": "$5,000",
      "fineAmount": 5000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Randomly switching lanes for no reason"
    },
    {
      "code": "T.C. 3.4.3",
      "title": "Failure to keep the distance",
      "category": "Moving & Driving Violations",
      "fine": "$5,000",
      "fineAmount": 5000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Not keeping distance from other cars on the road"
    },
    {
      "code": "T.C. 3.4.4",
      "title": "Hard braking",
      "category": "Moving & Driving Violations",
      "fine": "$20,000",
      "fineAmount": 20000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Breaking too quickly"
    },
    {
      "code": "T.C. 3.4.5",
      "title": "Creating an obstruction for overtaking",
      "category": "Moving & Driving Violations",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Not allowing another car to overtake"
    },
    {
      "code": "T.C. 3.5",
      "title": "Driving Under Influence",
      "category": "Moving & Driving Violations",
      "fine": "$20,000",
      "fineAmount": 20000,
      "sentence": "30 months",
      "sentenceMonths": 30,
      "class": "Felony (Class D)",
      "stars": "\u2b50\u2b50",
      "noBail": false,
      "remarks": "Operating a vehicle being drunk or under influence of drugs"
    },
    {
      "code": "T.C. 3.6.1",
      "title": "Participation in a street race",
      "category": "Moving & Driving Violations",
      "fine": "$15,000",
      "fineAmount": 15000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Taking part in a race on a public road"
    },
    {
      "code": "T.C. 3.6.2",
      "title": "Organizing a street race",
      "category": "Moving & Driving Violations",
      "fine": "$25,000",
      "fineAmount": 25000,
      "sentence": "30 months",
      "sentenceMonths": 30,
      "class": "Felony (Class D)",
      "stars": "\u2b50\u2b50",
      "noBail": false,
      "remarks": "Organizing a race on a public road"
    },
    {
      "code": "T.C. 5.2",
      "title": "Violation of the speed limit inside a special zone",
      "category": "Moving & Driving Violations",
      "fine": "$20,000",
      "fineAmount": 20000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Going over 90 km/h in a special zone mentioned in TC 5.4"
    },
    {
      "code": "T.C. 6.2.a",
      "title": "Parking on red curbs",
      "category": "Parking & Stopping Violations",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Vehicle may be towed on officer's descretion"
    },
    {
      "code": "T.C. 6.2.b",
      "title": "Interfiring with traffic following their lane",
      "category": "Parking & Stopping Violations",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Vehicle may be towed on officer's descretion"
    },
    {
      "code": "T.C. 6.2.c",
      "title": "Blocking exit from anywhere",
      "category": "Parking & Stopping Violations",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Vehicle may be towed on officer's descretion"
    },
    {
      "code": "T.C. 6.2.d",
      "title": "Parking on a crosswalk",
      "category": "Parking & Stopping Violations",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Vehicle may be towed on officer's descretion"
    },
    {
      "code": "T.C. 6.2.e",
      "title": "Blocking more than 2/3 of a sidewalk or bike path",
      "category": "Parking & Stopping Violations",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Vehicle may be towed on officer's descretion"
    },
    {
      "code": "T.C. 6.2.f",
      "title": "Parking on a driving lane",
      "category": "Parking & Stopping Violations",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Vehicle may be towed on officer's descretion"
    },
    {
      "code": "T.C. 6.2.g",
      "title": "Parking against direction of traffic",
      "category": "Parking & Stopping Violations",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Vehicle may be towed on officer's descretion"
    },
    {
      "code": "T.C. 6.2.h",
      "title": "Parking on bridges or in tunnels",
      "category": "Parking & Stopping Violations",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Vehicle may be towed on officer's descretion"
    },
    {
      "code": "T.C. 6.2.i",
      "title": "Parking on the highway or freeway",
      "category": "Parking & Stopping Violations",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Vehicle may be towed on officer's descretion"
    },
    {
      "code": "T.C. 6.2.j",
      "title": "Parking closer than 50 meters from a building on fire",
      "category": "Parking & Stopping Violations",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Vehicle may be towed on officer's descretion"
    },
    {
      "code": "T.C. 6.2.k",
      "title": "Parking at bus stops",
      "category": "Parking & Stopping Violations",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Vehicle may be towed on officer's descretion"
    },
    {
      "code": "T.C. 6.2.l",
      "title": "Parking on railway tracks or within the skidding of a wagon",
      "category": "Parking & Stopping Violations",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Vehicle may be towed on officer's descretion"
    },
    {
      "code": "T.C. 6.2.m",
      "title": "Parking in parking spaces marked in yellow",
      "category": "Parking & Stopping Violations",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Vehicle may be towed on officer's descretion"
    },
    {
      "code": "T.C. 6.2.n",
      "title": "Parking in violation of the road surface markings",
      "category": "Parking & Stopping Violations",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Vehicle may be towed on officer's descretion"
    },
    {
      "code": "T.C. 6.2.o",
      "title": "Parking closer than 20 meters from an entrance or exit",
      "category": "Parking & Stopping Violations",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Vehicle may be towed on officer's descretion"
    },
    {
      "code": "T.C. 6.2.p",
      "title": "Parking on lawns, in green spaces, and in places not intended for parking",
      "category": "Parking & Stopping Violations",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Vehicle may be towed on officer's descretion"
    },
    {
      "code": "T.C. 6.2.q",
      "title": "Parking in violation of Article 7",
      "category": "Parking & Stopping Violations",
      "fine": "$10,000",
      "fineAmount": 10000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": "Vehicle may be towed on officer's descretion"
    },
    {
      "code": "T.C. 6.4",
      "title": "Unauthorized presence of a vehicle on the territory of DOC",
      "category": "Moving & Driving Violations",
      "fine": "$15,000 + towing",
      "fineAmount": 15000,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "FALSE",
      "stars": "-",
      "noBail": false,
      "remarks": ""
    },
    {
      "code": "T.C. 8.1",
      "title": "The impound fees are set to be 10% of the state value of the vehicle. For example if the state value is $200,000, the impound fee is $20,000",
      "category": "Towing & Impounds",
      "fine": "",
      "fineAmount": 0,
      "sentence": "-",
      "sentenceMonths": 0,
      "class": "-",
      "stars": "-",
      "noBail": false,
      "remarks": ""
    }
  ],
  "speedLimits": [
    {
      "zone": "Public Roads (Non-highway)",
      "speed": "140 km/h",
      "desc": "All public roads excluding designated highways"
    },
    {
      "zone": "Highways & Freeways",
      "speed": "200 km/h",
      "desc": "All designated highways across San Andreas"
    },
    {
      "zone": "Special Zones",
      "speed": "90 km/h",
      "desc": "Capitol, Central Hospital, LSPD, SAHP, FIB, Casino, Power Plant, Amphitheaters, Auto Fair, Beach Market, Stations"
    }
  ],
  "specialZones": [
    "Capitol",
    "Central Hospital",
    "LSPD HQ",
    "SAHP Station",
    "FIB HQ",
    "Diamond Casino",
    "Power Plant",
    "Amphitheaters",
    "Auto Fair",
    "Beach Market",
    "Train & Metro Stations"
  ],
  "article7": {
    "legend": {
      "green": "Parking is allowed for all citizens",
      "orange": "Parking is allowed for state vehicles only",
      "red": "Parking is strictly prohibited for everyone",
      "blue": "Allowed parking direction"
    },
    "locations": [
      {
        "code": "TC 7.1.1",
        "name": "Capitol Building",
        "area": "Rockford Hills / Downtown",
        "rules": "Designated public stalls only, red curb violation results in immediate towing."
      },
      {
        "code": "TC 7.1.2",
        "name": "Diamond Casino & Resort",
        "area": "Vinewood East",
        "rules": "Valet and marked citizen parking lots only; blocking entrance or driveway is strictly prohibited."
      },
      {
        "code": "TC 7.1.3",
        "name": "Maze Bank Arena / Tower",
        "area": "Pillbox Hill",
        "rules": "Underground parking and designated bays; no parking along red-painted emergency lanes."
      },
      {
        "code": "TC 7.1.4",
        "name": "Los Santos Police Department (Mission Row HQ)",
        "area": "Mission Row",
        "rules": "Underground and front gated lots are Orange (State Vehicles Only). Citizen bays strictly limited to visitor slots."
      },
      {
        "code": "TC 7.1.5",
        "name": "San Andreas Highway Patrol HQ",
        "area": "Paleto Bay / Senora",
        "rules": "State vehicle bays reserved for SAHP interceptors; no civilian parking in motor pool."
      },
      {
        "code": "TC 7.1.6",
        "name": "Palmer-Taylor Power Plant",
        "area": "East Coast Highway",
        "rules": "Restricted industrial security zone. Unauthorized parked vehicles towed immediately."
      },
      {
        "code": "TC 7.1.7",
        "name": "Vespucci Beach Market",
        "area": "Vespucci Beach Promenade",
        "rules": "Vehicles strictly PROHIBITED on boardwalk and beach sand. Park in designated street bays outside."
      },
      {
        "code": "TC 7.1.8",
        "name": "Power Street / Adam's Apple Blvd",
        "area": "Downtown Los Santos",
        "rules": "High-traffic commercial corridor. Follow blue direction indicators; no double parking."
      },
      {
        "code": "TC 7.1.9",
        "name": "Postal Downtown",
        "area": "Textile City",
        "rules": "Loading dock bays reserved for postal vans and couriers. 15-minute max public drop-off."
      },
      {
        "code": "TC 7.1.10",
        "name": "Paleto Sawmill",
        "area": "Mount Chiliad Foothills",
        "rules": "Industrial heavy machinery zone. Keep clear of timber hauling lanes."
      },
      {
        "code": "TC 7.1.11",
        "name": "Grapeseed Farm 1",
        "area": "Grapeseed",
        "rules": "Agricultural access road. Do not block tractor pathways or crop fields."
      },
      {
        "code": "TC 7.1.12",
        "name": "Grapeseed Farm 2",
        "area": "Grapeseed",
        "rules": "Silo and warehouse parking in marked bays only."
      },
      {
        "code": "TC 7.1.13",
        "name": "Mirror Park Lake & Promenade",
        "area": "Mirror Park",
        "rules": "Park parallel in marked curb bays. Strictly no parking on green lawns, park walkways, or near pond."
      }
    ]
  },
  "deptCommands": {
    "dept-tab-bgc": {
      "title": "Background Check",
      "icon": "badge",
      "color": "#38bdf8",
      "commands": [
        {
          "title": "How Copy?",
          "text": "SAHP To ALL: How Copy?"
        },
        {
          "title": "Request BGC",
          "text": "SAHP To [DEPT/LAST]: (Name of person) wants to join SAHP. Can I have a BGC on them please?"
        },
        {
          "title": "BGC Result Clear",
          "text": "SAHP To [DEPT/LAST]: 10-4 BGC on (Name) is clean with no criminal history. Clear to proceed."
        },
        {
          "title": "10-4 Appreciated",
          "text": "SAHP To [DEPT/LAST]: 10-4! Appreciate your prompt assistance always!"
        }
      ]
    },
    "dept-tab-broadcasts": {
      "title": "Emergency Broadcasts",
      "icon": "campaign",
      "color": "#ef4444",
      "commands": [
        {
          "title": "Store Robbery",
          "text": "SAHP To ALL: Store Robbery in progress at [LOC]! Units respond Code 3!"
        },
        {
          "title": "Gun Store Robbery",
          "text": "SAHP To ALL: Gun Store Robbery in progress at [LOC]! High alert, suspect armed!"
        },
        {
          "title": "Hostage Situation",
          "text": "SAHP To ALL: Hostage Situation at [LOC]! Set up outer perimeter, negotiator enroute!"
        },
        {
          "title": "Officer Needs Help (11-99)",
          "text": "SAHP To ALL: 11-99! Trooper in distress at [LOC]! ALL AVAILABLE UNITS RESPOND CODE 3!"
        }
      ]
    },
    "dept-tab-bank": {
      "title": "Bank Robbery",
      "icon": "account_balance",
      "color": "#f59e0b",
      "commands": [
        {
          "title": "Bank Alarm Triggered",
          "text": "SAHP To ALL: 10-10 Bank Robbery alarm triggered! Establishing tactical perimeter."
        },
        {
          "title": "Request Heavy Backup",
          "text": "SAHP To LSPD/FIB/NG: Requesting all tactical units and barricades at Bank!"
        },
        {
          "title": "Hostages Negotiated",
          "text": "SAHP To ALL: Hostage negotiations concluded, prepare for tactical breach/pursuit!"
        },
        {
          "title": "Code 4 (All Clear)",
          "text": "SAHP To ALL: Bank secured, suspects in custody / neutralized. Scene is Code 4."
        }
      ]
    },
    "dept-tab-prison": {
      "title": "DOC & Prison",
      "icon": "lock",
      "color": "#f97316",
      "commands": [
        {
          "title": "10-17 Transport Announcement",
          "text": "[BADGE] To Dispatch: I am 10-17 to DOC with [NUMBER] of 10-15 and convoy."
        },
        {
          "title": "State Lawyer Request",
          "text": "[BADGE] To Dispatch: My 10-15 is requesting a state lawyer at DOC."
        },
        {
          "title": "Lawyer Arrival Confirmation",
          "text": "SAHP To State Lawyer: 10-4, meet at DOC front desk for suspect interrogation."
        },
        {
          "title": "10-99 Booking Completed",
          "text": "[BADGE] To Dispatch: Show my last 10-15 is now 10-99 and I am 10-19 to Paleto Bay SAHP HQ."
        }
      ]
    },
    "dept-tab-subs": {
      "title": "Aircraft Carrier / Subs",
      "icon": "directions_boat",
      "color": "#06b6d4",
      "commands": [
        {
          "title": "Carrier Assembly",
          "text": "SAHP To ALL: Units staging at marina/helipad for Aircraft Carrier operation!"
        },
        {
          "title": "Tactical Assault",
          "text": "SAHP To ALL: State convoy moving in. Watch elevated sniper positions and sea approach!"
        },
        {
          "title": "Carrier Secured",
          "text": "SAHP To ALL: Carrier objective secured! Safe return to patrol."
        }
      ]
    },
    "dept-tab-acc": {
      "title": "ACC Event",
      "icon": "domain",
      "color": "#10b981",
      "commands": [
        {
          "title": "ACC Deployment",
          "text": "SAHP To ALL: Heavy units deploying to ACC. Maintain defensive lines!"
        },
        {
          "title": "Barricades Deployed",
          "text": "SAHP To ALL: Tactical barricades deployed. Checkpoints active."
        },
        {
          "title": "ACC Victory",
          "text": "SAHP To ALL: ACC successfully defended. Great work troopers!"
        }
      ]
    },
    "dept-tab-meetings": {
      "title": "Meetings & Inter-Org",
      "icon": "groups",
      "color": "#a855f7",
      "commands": [
        {
          "title": "How Copy?",
          "text": "SAHP To [DEPT]: How copy?"
        },
        {
          "title": "Good Copy",
          "text": "SAHP To [DEPT/LAST]: Good copy, go ahead."
        },
        {
          "title": "Meeting Request",
          "text": "SAHP To [DEPT/LAST]: Can we have a quick command meeting at your HQ?"
        },
        {
          "title": "ETA 5 Mins",
          "text": "SAHP To [DEPT/LAST]: ETA to your HQ 5 minutes."
        },
        {
          "title": "Landing Permission",
          "text": "SAHP To [DEPT/LAST]: Air One requesting permission to land on your rooftop helipad."
        }
      ]
    }
  },
  "stateWaves": [
    {
      "wave": "Wave 1 (Start)",
      "steps": [
        "Dear Citizens of San Andreas, do you have what it takes to protect the highways and uphold justice?",
        "Join the San Andreas Highway Patrol and become the shield between law and chaos!",
        "Head over to Paleto Bay SAHP HQ as recruitment and interviews are happening right now!",
        "Requirements: Clean criminal record, health insurance, gun license, driver license, and no tattoos on hands or face.",
        "Obey and Survive! The state is counting on you to protect and serve."
      ]
    },
    {
      "wave": "Wave 2 (After 10 Mins)",
      "steps": [
        "Dear Citizens of San Andreas, this is SAHP High Command with an active recruitment update!",
        "SAHP interviews are still live at Paleto Bay HQ, but time is ticking fast!",
        "If you possess the courage, discipline, and desire to keep our state safe, report to SAHP lobby now!",
        "Must have a completely clean background, valid licenses, and professional appearance.",
        "Answer the call of duty and wear the badge with honor!"
      ]
    },
    {
      "wave": "Wave 3 (Final Call)",
      "steps": [
        "Final call San Andreas! SAHP recruitment doors will be closing in 10 minutes!",
        "This is your last chance this shift to join the ranks of the San Andreas Highway Patrol.",
        "Make your way to Paleto Bay HQ immediately with your passport and licenses ready.",
        "Clean record required, no facial or hand ink. Take your place among the finest troopers.",
        "SAHP recruitment concluding soon. We look forward to welcoming you to the force!"
      ]
    }
  ]
};

// Backwards compatibility alias
window.LSPD_DATA = window.SAHP_DATA;
